export enum NotificationType {
  // Notifications de modération
  REVIEW_NEEDS_MODERATION = 'REVIEW_NEEDS_MODERATION',
  REPORT_RECEIVED = 'REPORT_RECEIVED',
  
  // Notifications utilisateur
  REVIEW_APPROVED = 'REVIEW_APPROVED',
  REVIEW_REJECTED = 'REVIEW_REJECTED',
  
  // Notifications générales
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
  PROMOTION = 'PROMOTION',
  
  // Notifications de commande
  ORDER_STATUS_UPDATE = 'ORDER_STATUS_UPDATE',
  ORDER_CONFIRMATION = 'ORDER_CONFIRMATION',
  
  // Notifications de réservation
  RESERVATION_CONFIRMATION = 'RESERVATION_CONFIRMATION',
  RESERVATION_REMINDER = 'RESERVATION_REMINDER',
  
  // Notifications de fidélité
  LOYALTY_POINTS_ADDED = 'LOYALTY_POINTS_ADDED',
  REWARD_UNLOCKED = 'REWARD_UNLOCKED'
}
